### ISSUE TITLE
GWTGzipFilter doesn't work with Spring Boot

### ISSUE THREAD

**Issue by heyarny** [realityforge/gwt-cache-filter#5]
There is some kind of recursive error happening.

`
java.lang.StackOverflowError: null
	at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.getAttribute(Dispatcher.java:400) ~[jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.getAttribute(Dispatcher.java:400) ~[jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.getAttribute(Dispatcher.java:400) ~[jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.getAttribute(Dispatcher.java:400) ~[jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.getAttribute(Dispatcher.java:400) ~[jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.getAttribute(Dispatcher.java:400) ~[jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
	at org.eclipse.jetty.server.Dispatcher$IncludeAttributes.getAttribute(Dispatcher.java:400) ~[jetty-server-9.4.1.v20170120.jar:9.4.1.v20170120]
`

This is happening on GWTGzipFilter only.
The cache filter is working as intended.

**Comment by realityforge** [comment]
It seems it may be a bug in the way the container handles the way it is mapped. A similar bug is reported at https://bugs.eclipse.org/bugs/show_bug.cgi?id=444124 except this one is manifested by setAttribute call. However googling around it seems like there be other ways to trigger it. How is it being mapped - what does the web.xml fragment look like?

**Comment by heyarny** [comment]
Actually there is no web.xml in spring boot.
You just use beans to attach filters, like so:

`
@Configuration
public class WebFiltersConfig {

	@Bean
	public FilterRegistrationBean gwtCacheFilterRegistration() {
	    FilterRegistrationBean registration = new FilterRegistrationBean();
	    registration.setFilter(gwtCacheFilter());
	    registration.addUrlPatterns("/_res_user/*");
	    registration.setName("gwtCacheFilter");
	    return registration;
	}

	@Bean(name = "gwtCacheFilter")
	public Filter gwtCacheFilter() {
	    return new GWTCacheControlFilter();
	}

}
`

**Comment by realityforge** [comment]
If you change the line `registration.setName("gwtCacheFilter");` to `registration.setName("GWTGzipFilter");` does it work? The underlying filter has a different name and this may fix it if spring boot does any annotation scanning.

**Comment by heyarny** [comment]
@realityforge that didn't work either

**Comment by realityforge** [comment]
Unfortunately I don't have any more ideas but if you come up with something please post back here

**Comment by realityforge** [comment]
Closing this as no ability to reproduce and long period of no activity
